package com.taotao.portal.pojo;

import com.taotao.pojo.TbItem;

/**
 * avoid to modify TbItem directly,generally we choose to extends the pojo generated by MGB
 * @author mbc1996
 *
 */
public class ItemBaseInfo extends TbItem {
	
	public String[] getImages(){
		if(this.getImage() != null){
			return this.getImage().split(",");
		}else{
			return null;
		}
	}
}
